In [46]:
import numpy as np
from numpy.linalg import cond, norm
import time
import matplotlib.pyplot as plt
from scipy.linalg import hilbert
from math import sin, cos, pow

from prettytable import PrettyTable

%matplotlib inline

In [47]:
# Problem 4
# Hilbert matrices

In [48]:
# part a

n_low = 8
n_high = 12

n_array = np.array(range(n_low, n_high + 1))
cond_list = []

for n in n_array:
    curr_hilb = hilbert(n)
    cond_list.append(cond(curr_hilb))

table = PrettyTable()
table.field_names = ["Hilbert matrix size (N)", "condition number"]
table.add_rows(
    [
        [n, f"{cond_num: e}"] for n, cond_num in zip(n_array, cond_list)
    ]
)

print(table)

+-------------------------+------------------+
| Hilbert matrix size (N) | condition number |
+-------------------------+------------------+
|            8            |   1.525758e+10   |
|            9            |   4.931534e+11   |
|            10           |   1.602503e+13   |
|            11           |   5.220207e+14   |
|            12           |   1.621164e+16   |
+-------------------------+------------------+


In [49]:
# part d

n_low = 8
n_high = 12

n_array = np.array(range(n_low, n_high + 1))
hilb_list = []
b_list = []
x_list = []

for n in n_array:
    curr_hilb = hilbert(n)

    # use formula for b given (sum of the rows in A)
    curr_b = np.sum(curr_hilb, axis=1)

    curr_x = np.linalg.solve(np.copy(curr_hilb), np.copy(curr_b))

    hilb_list.append(curr_hilb)
    b_list.append(curr_b)
    x_list.append(curr_x)

# format to print 16 digits of precision
float_formatter = "{:.16f}".format
np.set_printoptions(formatter={'float_kind': float_formatter})

table = PrettyTable()
table.field_names = ["Hilbert matrix size (N)", "solution vector x"]
table.add_rows(
    [
        [n, x] for n, x in zip(n_array, x_list)
    ]
)

print(table)

# remember to reset the print options for numpy
np.set_printoptions(formatter={'float_kind': None})

+-------------------------+------------------------------------------------------------+
| Hilbert matrix size (N) |                     solution vector x                      |
+-------------------------+------------------------------------------------------------+
|            8            | [0.9999999999681907 1.0000000016822066 0.9999999782000777  |
|                         |  1.0000001174172146 0.9999996848830713 1.0000004448897650  |
|                         |           0.9999996839051423 1.0000000890763439]           |
|            9            | [0.9999999998088036 1.0000000130887288 0.9999997796130058  |
|                         |  1.0000015674037004 0.9999942673865873 1.0000116780493731  |
|                         |  0.9999866137742437 1.0000080725488052 0.9999980081985083] |
|            10           | [0.9999999988121090 1.0000001004503016 0.9999978957924024  |
|                         |  1.0000188750065389 0.9999109586890151 1.0002425099467109  |
|                    

In [56]:
# part f
# use the lists from above

relative_error_solution_list = []
residual_list = []

for n, hilb, b, x in zip(n_array, hilb_list, b_list, x_list):
    x_true = np.ones((n, ))
    print(f"{x_true}")
    print(f"{x}")
    curr_relative_error_solution = norm(x_true - x) / norm(x_true)

    curr_residual = norm(b - hilb @ x) / norm(b)

    relative_error_solution_list.append(curr_relative_error_solution)
    residual_list.append(curr_residual)

table = PrettyTable()
table.field_names = ["Hilbert matrix size (N)", "relative error in solution", "residual"]
table.add_rows(
    [
        [n, f"{relative_error_solution: e}", residual]
        for n, relative_error_solution, residual in zip(n_array,
                                                        relative_error_solution_list,
                                                        residual_list)
    ]
)

print(table)

[1. 1. 1. 1. 1. 1. 1. 1.]
[1.         1.         0.99999998 1.00000012 0.99999968 1.00000044
 0.99999968 1.00000009]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1.         1.00000001 0.99999978 1.00000157 0.99999427 1.00001168
 0.99998661 1.00000807 0.99999801]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1.         1.0000001  0.9999979  1.00001888 0.99991096 1.00024251
 0.99960526 1.00037886 0.9998023  1.00004325]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1.         1.00000042 0.99998931 1.00011726 0.99931274 1.00238324
 0.99487192 1.00691959 0.99430378 1.00261458 0.99948717]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.99999995 1.00000591 0.99981585 1.0024906  0.98185224 1.07933194
 0.7799196  1.39687856 0.53623881 1.33866309 0.85955814 1.02524533]
+-------------------------+----------------------------+------------------------+
| Hilbert matrix size (N) | relative error in solution |        residual        |
+-------------------------+----------------------------+------------------------+
|            8            |  

In [51]:
# Problem 6
# Cancellation, Precision and Loss of Precision

In [52]:
# part a

f = lambda x: (1 - cos(x)) / pow(x, 2)
x_val = 1.2e-8

table = PrettyTable()
table.field_names = ["x", "f(x)"]
table.add_rows(
    [
        [x_val, f(x_val)]
    ]
)

print(table)

+---------+--------------------+
|    x    |        f(x)        |
+---------+--------------------+
| 1.2e-08 | 0.7709882115452477 |
+---------+--------------------+


In [53]:
# part c

# f = lambda x: (1 - (1 - (2 * pow(sin(x / 2), 2)))) / pow(x, 2)
f = lambda x: (2 * pow(sin(x / 2), 2)) / pow(x, 2)
x_val = 1.2e-8

table = PrettyTable()
table.field_names = ["x", "f(x)"]
table.add_rows(
    [
        [x_val, f(x_val)]
    ]
)

print(table)

+---------+------+
|    x    | f(x) |
+---------+------+
| 1.2e-08 | 0.5  |
+---------+------+


In [54]:
print("a")

a
